### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/2factor_auth#12]
Bissl Beschreibung

**Comment by alexplusde** [comment]
Bitte mal draufschauen, ob noch was fehlt für den Moment.

**Comment by staabm** [comment]
vllt ein screenshot, aber textuell schon super. danke.

closed by https://github.com/FriendsOfREDAXO/2factor_auth/commit/ae9b2660036680f3b700589f1d367621b0c8b6ad

**Comment by alexplusde** [comment]
> vllt ein screenshot, aber textuell schon super. danke.

Klar - wenn die Optik feststeht. :)

**Comment by alexplusde** [comment]
@staabm kannst du noch die README.md in die GUI einbinden?

```
    2factor_auth_help: 
        title: Hilfe
        SubPath: README.md
        itemclass: pull-right 
```

ich habe bei der package.yml nach wie vor nicht den Überblick, wann ich page, pages, subpages, etc. definieren muss und wie der Pfad lauten muss - es wird in diesem Addon der Reiter "Hilfe" einfach nicht angezeigt.
